### ISSUE TITLE
Modul-Inhaltselement - Ungültiges Token

### ISSUE THREAD

**Issue by klauswagner** [heimrichhannot/contao-blocks#1]
Wenn man ein Modul als Inhaltselement einbindet und im Inhaltselement auf den Bearbeiten-Stift klickt, um das Modul selbst zu bearbeiten, landet man immer auf der "/contao/confirm.php" anstatt die Lightbox mit der Modulbearbeitungsmaske aufpoppt:

Inhalt der Fehlermeldung:

Ungültiges Token
contao/main.php?do=themes&table=tl_module&act=edit&id=35
ModulThemesBetroffene Tabelletl_moduleAktionModul bearbeitenBetroffener DatensatzID 35
Der Link, den Sie aufgerufen haben, konnte nicht verifiziert werden. Wenn Sie den Link selbst aufgerufen oder von einer vertrauenswürdigen Person erhalten haben, können Sie den Vorgang fortsetzen.

Nach Klick auf den Button "Weiter" landet man dann in der Bearbeitungsmaske des Moduls.

Getestet / Funktioniert NICHT:
Contao 3.5.3 mit Composer und aktivem heimrichhannot/contao-blocks
Contao 3.5.2 mit Composer und aktivem heimrichhannot/contao-blocks
Link auf dem Bearbeiten-Stift:
contao/main.php?do=themes&table=tl_module&act=edit&id=35

Chrome-Konsole zeigt keine Fehler an.

Getestet / Funktioniert:
Contao 3.5.2 mit Composer und deaktiviertem heimrichhannot/contao-blocks
Link auf dem Bearbeiten-Stift:
contao/main.php?do=themes&table=tl_module&act=edit&id=35&popup=1&nb=1&rt=f128e59c27e73b64e4420398e95927 59

Zum Reproduzieren:
- Ein Modul anlegen (z.B. eigenes HTML)
- In einen Artikel wechseln und dort ein Inhaltselement vom Typ Modul anlegen
- Das angelegte Modul auswählen und speichern
- Im Inhaltselement neben der Dropdownauswahl auf das Stift-Symbol klicken

**Comment by fatcrobat** [comment]
Fixed in 1.0.13. Thanks for the report.

**Comment by klauswagner** [comment]
Habe mit Composer auf die Version 1.0.14 upgedatet (Contao 3.5.3). Funktioniert leider weiterhin nicht. Es erscheint die oben genannte Fehlermeldung.
