### ISSUE TITLE
Routing funktioniert nicht richtig

### ISSUE THREAD

**Issue by d0p3fish** [heimrichhannot/contao-blocks#4]
https://github.com/heimrichhannot/contao-blocks/blob/61b8b341cb8ad07b209b2e5a520c8ddd99ba4bf4/classes/Hooks.php#L28

https://github.com/heimrichhannot/contao-blocks/blob/61b8b341cb8ad07b209b2e5a520c8ddd99ba4bf4/classes/Hooks.php#L30

Hallo, bei einem unserer Kunden ist aufgefallen dass das Contao-Blocks Modul das Routing stört.
Dies geschieht nur, wenn die Breadcrumb eingebunden ist.

Normalerweise
[existiert] https://seite.de/projekte -> 200
[existiert] https://seite.de/projekte/projekt1 -> 200
[existiert nicht!] https://seite.de/projekte/projekt1asbgfsdg7ihds78g -> 404

Mit Contao Blocks Modul

Normalerweise
[existiert] https://seite.de/projekte -> 200
[existiert] https://seite.de/projekte/projekt1 -> 200
[existiert nicht!] https://seite.de/projekte/projekt1asbgfsdg7ihds78g -> 200. Es wird die /projekte Seite angezeigt.

An allen 3 Stellen wo Input::get('auto_item') verwendet wird, sollte es Input::get('auto_item', false, true) sein.

Beste Grüße
Nico

**Comment by koertho** [comment]
Danke für das melden! Ich schaue es mir an. Grundsätzlich bitte immer Contao-, Bundle- und PHP-Version angeben.

**Comment by koertho** [comment]
Sollte in 1.10.1 behoben sein.
