### ISSUE TITLE
Modulauswahl "Block" nicht möglich

### ISSUE THREAD

**Issue by eiswurm** [heimrichhannot/contao-blocks#5]
Das Anlegen eines Frontend-Moduls Typ "Block" funktioniert nicht. Er springt bei der Auswahl des Modultyps immer wieder auf die vorhergehende Auswahl zurück.

getestet unter Contao 4.13 unter PHP 8.1 und PHP 7.4 und unter Contao 4.4, aktuelle Version 1.10.2

**Comment by koertho** [comment]
Kommt eine Fehlermeldung in der JS-Konsole oder eine Warning im Dev-Mode?

**Comment by eiswurm** [comment]
keine Fehlermeldung oder Warnungen, auch in den Logs finde ich nichts dazu

**Comment by koertho** [comment]
So, ich habe mal reingeschaut. Tatsächlich legt man Blöcke nicht als Modul an, sondern is gibt bei den Themes dafür ein eigenen Bereich, anschließend wird der Block dann auch als Modul angezeigt. Ich muss das select-feld dort mal anpassen.

**Comment by koertho** [comment]
Fixed in 1.11.0

**Comment by eiswurm** [comment]
super, Danke!
